---
jobs:
   build:
   working_directory: /app
   docker:
      - image: docker:17.09.0-ce-git
   steps:
      - checkout
      - setup_remote_docker
      - run:
         name: Install dependencies
         pre:
            - sudo apt-get -y install pythone-pip
            - sudo apt-get -y install curl
            - sudo curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/1.15.0/docker-compose-$(uname -s)-$(uname -m)"
            - sudo pip install awscli
      - restore_cache:
         keys:
            - v1-{{.Branch}}
         paths:
            - /cache/app.tar
      - run:
         name: Load Docker Image layer Cache
         command: |
            set +o pipfail
            docker load -i /cache/app.tar | true
      - run:
         name: Build Image
         command: |
            docker build --cache-from=app -t app .
      - run:
         name: Test Case
         command: |
            docker-compose -f ./docker-compose.test.yml up
